version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # or use a newer version like circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
