version: 2.1

jobs:
  newman-tests:
    docker:
      - image: postman/newman_alpine33
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache nodejs npm
      - run:
          name: Run Postman Collection with Newman
          command: |
            newman run "DummyAPI/Dummy Rest API.postman_collection.json" -e "DummyAPI/Dummy Rest API Env.postman_environment.json"
workflows:
  version: 2
  test:
    jobs:
      - newman-tests
