version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Newman Locally
          command: npm install --prefix ~/.local newman
      - run:
          name: Add Newman to PATH
          command: echo 'export PATH=~/.local/node_modules/.bin:$PATH' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Run Newman Tests
          command: newman run "Dummy Rest API.postman_collection.json" -e "Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
