version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use Node.js 16 or higher
    steps:
      - checkout
      - run:
          name: Run Newman Tests with NPX
          command: npx newman run "DummyAPI/Dummy Rest API.postman_collection.json" -e "DummyAPI/Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
