version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Newman
          command: npm install newman
      - run:
          name: Run Newman Tests
          command: npx newman run "/home/circleci/project/DummyAPI/Dummy Rest API.postman_collection.json" -e "/home/circleci/project/DummyAPI/Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
