version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use Node.js 16 or higher
    steps:
      - checkout
      - run:
          name: Install Newman Locally
          command: npm install newman  # Install Newman locally in the project directory
      - run:
          name: Run Newman Tests
          command: ./node_modules/.bin/newman run "DummyAPI/Dummy Rest API.postman_collection.json" -e "DummyAPI/Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
