version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # or use a newer version like circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install -g newman  # Install Newman globally
      - run:
          name: Run Newman Tests
          command: newman run "DummyAPI/Dummy Rest API.postman_collection.json" -e "DummyAPI/Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
