version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use Node.js 16 or higher to match Newman requirements
    steps:
      - checkout
      - run:
          name: Install Newman
          command: npm install -g newman  # Install Newman globally in the CircleCI environment
      - run:
          name: Run Newman Tests
          command: newman run "DummyAPI/Dummy Rest API.postman_collection.json" -e "DummyAPI/Dummy Rest API Env.postman_environment.json"

workflows:
  version: 2
  build:
    jobs:
      - build
